require(dplyr)
require(UsingR)
require(HistData)
require(MASS)
require(lattice)

data("kid.weights")
data("michelson")
data("fat")
data("SAT")
data("heartrate")
data("grades")
data("Fingerprints")
data("Titanic")
data("morley")
data("Cars93")
data("ToothGrowth") #not part of UsingR
data(PearsonLee)
attach(kid.weights)
attach(michelson)
attach(fat)
attach(SAT)
attach(heartrate)
attach(grades)
attach(Fingerprints)
attach(Cars93)
attach(Titanic)
attach(morley)
attach(PearsonLee)
# use data() to see all datasets
# #use answers() to get answers to some of the problems in the UsingR book

